/*
 * sample API
 *
 * This is sample.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// PetsIdGet - 
func (s *DefaultApiService) PetsIdGet(ctx context.Context, id int64) (ImplResponse, error) {
	// TODO - update PetsIdGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Pets{}) or use other options such as http.Ok ...
	//return Response(200, Pets{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("PetsIdGet method not implemented")
}

